### ISSUE TITLE
Windows threads support

### ISSUE THREAD

**Issue by jimon** [jtsiomb/c11threads#4] opened 2016-06-26 18:36 UTC
Would be really nice to see win threads support here! I might do it because I'm quite desperate looking for C-only cross-platform threading lib.

**Comment by jtsiomb** [comment] 2016-06-26 23:12
I might be missing something, but what would networking have to do with a C11 threads implementation?

**Comment by jimon** [comment] 2016-06-27 08:02
There are very few threads.h implementations atm, and looks like no implementation for Windows. threads.h meant to be platform-independent header, so would be nice to add win support in one place, otherwise community will end-up with two different headers :(

**Comment by jimon** [comment] 2016-06-27 08:03
Probably most of stuff could be copy-pasted from here https://github.com/tinycthread/tinycthread with saving license note.

**Comment by jtsiomb** [comment] 2016-06-27 15:09
So you meant "windows threads", not "windows sockets". Then sure, it would be nice to have C11 threads on windows.

But I don't think this is the place to do that. I have implemented pthreads on windows in the past, and the problem is the win32 API doesn't have a condvar-equivalent construct. This means that a full implementation of C11 threads can't really be a header-only thin wrapper, but rather a full library, like the one you linked. So I suggest using that one instead if you care about windows compatibility.

Still, having said that, if someone cares to contribute a win32 implementation to this "project", and it's clean and well written enough, I will include it.

**Comment by jimon** [comment] 2016-06-27 15:57
Ah yes, threads! it was too late in the evening :)

**Comment by oold** [comment] 2022-12-21 22:52
> the win32 API doesn't have a condvar-equivalent construct

Mesa has a header-only implementation [1] and it uses the Win32 functions for condition variables.

[1] [https://gitlab.freedesktop.org/mesa/mesa/-/blob/22.1/include/c11/threads_win32.h]()

**Comment by jtsiomb** [comment] 2022-12-21 23:22
Nice, I guess they added condition variables to win32 at some point. It was later than the last time I had to deal with win32 programming though. It's only available on windows vista and later.

Nevertheless, that sounds like a good candidate for a windows port of c11threads. So as I said previously, if anyone cares to contribute a windows implementation of all this, I'll be glad to review any pull requests or patches.

**Comment by jtsiomb** [comment] 2023-01-04 21:28
Pull request #21 adding support for win32 has been merged.

**Closed as completed by jtsiomb** 2023-01-04 21:28 UTC
Labels: enhancement
